const usageMessage = [
    'All options in alphabetical order:',
    '',
    '   --angularCli: is just a synonym for --plainVertical',
    "   --clarificationsFile [filepath]: A file that describe the license clarifications for each package, see clarificationExample.json, any field available to the customFormat option can be clarified. Can also be used to specify a subregion of a package's license file (instead reading the entire file)",
    '   --csv: output in csv format',
    '   --csvComponentPrefix: column prefix for components in csv file',
    '   --customPath: to add a custom Format file in JSON',
    '   --development: only show development dependencies',
    '   --depth [number]: look for "number" of levels of dependencies - overrides the ambiguously named "--direct" option',
    '   --direct [boolean|number]: look for direct dependencies only if "true" or look for "number" of levels of dependencies',
    '   --excludeLicenses [list]: exclude modules which licenses are in the comma-separated list from the output',
    '   --excludePackages [list]: restrict output to the packages (either "package@fullversion" or "package@majorversion" or only "package") NOT in the semicolon-seperated list',
    '   --excludePackagesStartingWith [list]: excludes packages starting with anything the comma-separated list',
    '   --excludePrivatePackages: restrict output to not include any package marked as private',
    '   --failOn [list]: fail (exit with code 1) on the first occurrence of the licenses of the semicolon-separated list',
    '   --files [path]: copy all license files to path and rename them to `module-name`@`version`-LICENSE.txt',
    '   --includeLicenses [list]: restrict output to the packages of which the licenses are included in the comma-separated list from the output',
    '   --includePackages [list]: restrict output to the packages (either "package@fullversion" or "package@majorversion" or only "package") in the semicolon-seperated list',
    '   --json: output in json format',
    '   --limitAttributes [list]: limit the attributes to be output',
    '   --markdown: output in markdown format',
    '   --nopeer: skip peer dependencies in output',
    '   --onlyAllow [list]: fail (exit with code 1) on the first occurrence of the licenses not in the semicolon-seperated list',
    '   --onlyunknown: only list packages with unknown or guessed licenses',
    '   --out [filepath]: write the data to a specific file',
    '   --plainVertical: output in plain vertical format like [Angular CLI does](https://angular.io/3rdpartylicenses.txt)',
    '   --production: only show production dependencies',
    '   --relativeLicensePath: output the location of the license files as relative paths',
    '   --relativeModulePath: output the location of the module files as relative paths',
    '   --start [filepath]: path of the initial json to look for',
    '   --summary: output a summary of the license usage',
    '   --unknown: report guessed licenses as unknown licenses',
    '',
    '   --version: The current version',
    '   --help: The text you are reading right now :)',
    '',
].join('\n');

export { usageMessage };
